name: Deploy
on: 
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      
      - name: Install node
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run test

  test:
    needs: [ lint ]
    runs-on: ubuntu-latest
    outputs:
      srcipt-file: ${{ steps.filename.outputs.srcipt-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish js file name
        id: filename
        run: echo 'script-file=index' >> $GITHUB_OUTPUT';'
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: |
            dist
            package.json
  deploy:
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: get artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: Output contents
        run: ls
      - name: Output file name
        run: echo "${{ needs.test.output.script-file }}"
      - name: Deploy
        run: echo "deploy "
